[project]
name = "cf-fastapi-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HaeengIn", email = "haeengin@gmail.com" }
]
requires-python = ">=3.12.1"
dependencies = [
    "auto-template>=1.0.0",
    "fastapi[standard]>=0.141.1",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
cf-fastapi-test = "cf_fastapi_test:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
